
pum:
  migration_table_schema: tce_sys
  minimum_version: 1.1.12

roles:
  - name: tce_viewer
    description: Role for users who can view the tce data.
    permissions:
      - type: read
        schemas: [tce_od, tce_vl, tce_sys, tce_app, tce_cfg]

  - name: tce_user
    description: Role for users who can view and edit the tce data.
    inherit: tce_viewer
    permissions:
      - type: write
        schemas: [tce_od]

  - name: tce_manager
    description: Role for users who can view and edit the tce data, and manage the tce application.
    inherit: tce_user
    permissions:
      - type: write
        schemas: [tce_vl, tce_cfg]

  - name: tce_sysadmin
    description: Role for system administrators who can manage the tce application and its configuration.
    inherit: tce_manager
    permissions:
      - type: write
        schemas: [tce_sys]


parameters:
  - name: SRID
    type: integer
    default: 2056
    description: Coordinate Reference System (CRS) to use for the data. This is used for the geometry column in the database. Default is 2056 (CH1903+ / LV95).

  - name: tce_reach_extra
    type: text
    description: YAML file with extra information for the tce_reach view.

  - name: tce_cemetery_structure_extra
    type: text
    description: YAML file with extra information for the tce_cemetery_structure view.

  - name: tce_ii_extra
    type: text
    description: YAML file with extra information for the vw_tce_infiltration_installation_extra view.

  - name: cemetery_structure_extra
    type: text
    description: YAML file with extra information for the cemetery_structure view.

  - name: tce_channel_extra
    type: text
    description: YAML file with extra information for the vw_tce_channel_extra view.

  - name: lang_code
    type: text
    description: language code for the creation of custom views

dependencies:
  - name: pirogue
    minimum_version: 3.0.0

migration_hooks:
  pre:
    - code: DROP SCHEMA IF EXISTS tce_app CASCADE;
  post:
    - file: app/create_app.py

# demo_data:
#  - name: Aletsch
#    file: demo_data/demo_data_aletsch.sql
