------------------------------------------
/* GRANT on schemas - once per database */
------------------------------------------

/* Viewer */
GRANT USAGE ON SCHEMA tce_od  TO tce_viewer;
GRANT USAGE ON SCHEMA tce_sys TO tce_viewer;
GRANT USAGE ON SCHEMA tce_vl  TO tce_viewer;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA tce_od  TO tce_viewer;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA tce_sys TO tce_viewer;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA tce_vl  TO tce_viewer;

GRANT SELECT, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA tce_od  TO tce_viewer;
GRANT SELECT, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA tce_sys TO tce_viewer;
GRANT SELECT, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA tce_vl  TO tce_viewer;

ALTER DEFAULT PRIVILEGES IN SCHEMA tce_od  GRANT SELECT, REFERENCES, TRIGGER ON TABLES TO tce_viewer;
ALTER DEFAULT PRIVILEGES IN SCHEMA tce_sys GRANT SELECT, REFERENCES, TRIGGER ON TABLES TO tce_viewer;
ALTER DEFAULT PRIVILEGES IN SCHEMA tce_vl  GRANT SELECT, REFERENCES, TRIGGER ON TABLES TO tce_viewer;

/* User */
GRANT ALL ON SCHEMA tce_od TO tce_user;
GRANT ALL ON ALL TABLES IN SCHEMA tce_od TO tce_user;
GRANT ALL ON ALL SEQUENCES IN SCHEMA tce_od TO tce_user;

ALTER DEFAULT PRIVILEGES IN SCHEMA tce_od GRANT ALL ON TABLES TO tce_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA tce_od GRANT ALL ON SEQUENCES TO tce_user;

DO $$ BEGIN EXECUTE 'GRANT CREATE ON DATABASE ' || (SELECT current_database()) || ' TO "tce_user"'; END $$;  -- required for ili2pg imports/exports

/* Manager */
GRANT ALL ON SCHEMA tce_vl TO tce_manager;
GRANT ALL ON ALL TABLES IN SCHEMA tce_vl TO tce_manager;
GRANT ALL ON ALL SEQUENCES IN SCHEMA tce_vl TO tce_manager;
ALTER DEFAULT PRIVILEGES IN SCHEMA tce_vl GRANT ALL ON TABLES TO tce_manager;
ALTER DEFAULT PRIVILEGES IN SCHEMA tce_vl GRANT ALL ON SEQUENCES TO tce_manager;

/* SysAdmin */
GRANT ALL ON SCHEMA tce_sys TO tce_sysadmin;
GRANT ALL ON ALL TABLES IN SCHEMA tce_sys TO tce_sysadmin;
GRANT ALL ON ALL SEQUENCES IN SCHEMA tce_sys TO tce_sysadmin;
ALTER DEFAULT PRIVILEGES IN SCHEMA tce_sys GRANT ALL ON TABLES TO tce_sysadmin;
ALTER DEFAULT PRIVILEGES IN SCHEMA tce_sys GRANT ALL ON SEQUENCES TO tce_sysadmin;

/*
-- Revoke

REVOKE ALL ON SCHEMA tce_od  FROM tce_viewer;
REVOKE ALL ON SCHEMA tce_sys FROM tce_viewer;
REVOKE ALL ON SCHEMA tce_vl  FROM tce_viewer;

REVOKE ALL ON ALL TABLES IN SCHEMA tce_od  FROM tce_viewer;
REVOKE ALL ON ALL TABLES IN SCHEMA tce_sys FROM tce_viewer;
REVOKE ALL ON ALL TABLES IN SCHEMA tce_vl  FROM tce_viewer;

ALTER DEFAULT PRIVILEGES IN SCHEMA tce_od  REVOKE ALL ON TABLES  FROM tce_viewer;
ALTER DEFAULT PRIVILEGES IN SCHEMA tce_sys REVOKE ALL ON TABLES  FROM tce_viewer;
ALTER DEFAULT PRIVILEGES IN SCHEMA tce_vl  REVOKE ALL ON TABLES  FROM tce_viewer;

*/
